# Generated by Django 4.1.2 on 2022-10-27 11:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lyric',
            name='age',
        ),
        migrations.RemoveField(
            model_name='lyric',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='lyric',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='song',
            name='age',
        ),
        migrations.RemoveField(
            model_name='song',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='song',
            name='last_name',
        ),
        migrations.AddField(
            model_name='lyric',
            name='content',
            field=models.CharField(default=1, max_length=1500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='date_released',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AddField(
            model_name='song',
            name='likes',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='title',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='artiste',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='artiste',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='artiste',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
    ]
